export const STORE_KEY_TOKEN = 'user.token'
export const STORE_KEY_TOKEN_ADRRESS = 'user.token.address'
export const STORE_KEY_WALLET_TYPE = 'wallet.type'
export const STORE_KEY_WALLET_CONNECTED = 'wallet.connected'
export const STORE_KEY_WALLET_CONSTAST_TYPE = 'wallet.constast.type'
